#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Jul 21 23:08:39 2017

@author: ashish
"""

from sklearn.cross_validation import train_test_split
from Decision_Boundary import plot_decision_regions
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
from sklearn.svm import SVC
import matplotlib.pyplot as plt
import numpy as np

iris = load_iris()
X, y = iris.data[:, [2,3]], iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

svm = SVC(kernel='linear', C=1.0, random_state=0)
svm.fit(X_train_std, y_train)

X_combine = np.vstack((X_train_std, X_test_std))
y_combine = np.hstack((y_train, y_test))

plot_decision_regions(X_combine, y_combine, classifier=svm, test_idx=range(105,150))
plt.xlabel('petal length')
plt.ylabel('petal width')
plt.legend(loc='upper left')
plt.show()